#!/bin/bash
 
NAME="treeio" # Name of the application
DJANGODIR=/path/treeio/treeio # Django project directory
DJANGORUNDIR=/path/gedocorp/treeio
SOCKFILE=/path/treeio/run/gunicorn.sock # we will communicte using this unix socket
USER=treeio # the user to run as
GROUP=treeio # the group to run as
NUM_WORKERS=3 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=treeio.settings # which settings file should Django use
DJANGO_WSGI_MODULE=treeio.wsgi 
 
echo "Starting $NAME"
 
# Activate the virtual environment
cd $DJANGODIR
source ./venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGORUNDIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ./venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--log-level=debug \
--bind=unix:$SOCKFILE
